export const BANG_COMMANDS = {
    '!g': { url: 'https://www.google.com/search?q=', name: 'Google' },
    '!ddg': { url: 'https://duckduckgo.com/?q=', name: 'DuckDuckGo' },
    '!yt': { url: 'https://www.youtube.com/results?search_query=', name: 'YouTube' },
    '!w': { url: 'https://tr.wikipedia.org/w/index.php?title=Özel:Ara&search=', name: 'Wikipedia (TR)' },
    '!e': { url: 'https://www.ekşisözlük.com/search/?q=', name: 'Ekşi Sözlük' },
    '!gh': { url: 'https://github.com/search?q=', name: 'GitHub' },
    '!a': { url: 'https://artadosearch.com/search?i=', name: 'Artado Search' },
    '!tw': { url: 'https://twitter.com/search?q=', name: 'Twitter' },
    '!fb': { url: 'https://www.facebook.com/search/top?q=', name: 'Facebook' },
    '!li': { url: 'https://www.linkedin.com/search/results/all/?keywords=', name: 'LinkedIn' },
    '!in': { url: 'https://www.instagram.com/explore/tags/', name: 'Instagram' },
    '!rd': { url: 'https://www.reddit.com/search/?q=', name: 'Reddit' },
    '!so': { url: 'https://stackoverflow.com/search?q=', name: 'Stack Overflow' },
    '!wp': { url: 'https://wordpress.org/search/', name: 'WordPress' },
    '!mdn': { url: 'https://developer.mozilla.org/en-US/search?q=', name: 'MDN Web Docs' },
    '!w3': { url: 'https://www.w3schools.com/search/default.asp?q=', name: 'W3Schools' },
    '!cs': { url: 'https://css-tricks.com/search/', name: 'CSS-Tricks' },
    '!py': { url: 'https://docs.python.org/3/search.html?q=', name: 'Python Docs' },
    '!node': { url: 'https://nodejs.org/api/', name: 'Node.js Docs' },
    '!react': { url: 'https://react.dev/search?q=', name: 'React Docs' },
    '!vue': { url: 'https://vuejs.org/guide/search.html?q=', name: 'Vue.js Docs' },
    '!svelte': { url: 'https://svelte.dev/search?q=', name: 'Svelte Docs' },
    '!npm': { url: 'https://www.npmjs.com/search?q=', name: 'npm' },
    '!pypi': { url: 'https://pypi.org/search/?q=', name: 'PyPI' },
    '!docker': { url: 'https://hub.docker.com/search?q=', name: 'Docker Hub' },
    '!aws': { url: 'https://aws.amazon.com/search?q=', name: 'AWS' },
    '!azure': { url: 'https://azure.microsoft.com/en-us/search/', name: 'Azure' },
    '!gcp': { url: 'https://cloud.google.com/search?q=', name: 'GCP' },
    '!news': { url: 'https://news.google.com/search?q=', name: 'Google News' },
    '!maps': { url: 'https://www.google.com/maps/search/', name: 'Google Maps' },
    '!translate': { url: 'https://translate.google.com/?sl=tr&tl=en&text=', name: 'Google Translate' },
    '!dict': { url: 'https://www.google.com/search?q=define+', name: 'Dictionary' },
    '!weather': { url: 'https://www.google.com/search?q=weather+', name: 'Weather' },
    '!time': { url: 'https://www.google.com/search?q=time+', name: 'Time' },
};
